title: My Site Title
author: Roger Symonds
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  awesome blog test test-site
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: rogersymonds # DO NOT include the @ character, or else the build will fail!
github_username:  rsymo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
